version: "3.7"

services:
  app:
    build: 
      context: ./bikes-app
      args:
        user: bikes
        uid: 1000
    ports:
      - 9000:9000
      - 9001:9001
    working_dir: /var/www/html
    volumes:
      - ./bikes-app/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./bikes/:/var/www/html
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1010
      MYSQL_DB: laravel
    links:
      - mysql
    networks:
      - bridge
    command: >
      bash -c "php artisan config:clear
      && php artisan migrate
      && npm install
      && npm run prod
      && php artisan bikes:update"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 1010
      MYSQL_DATABASE: laravel
    networks:
      - bridge

  web:
    image: nginx:1.19-alpine
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    ports:
      - 8000:80
    volumes:
      - ./bikes/:/var/www/html
    links:
      - app
      - mysql
    networks:
      - bridge

networks: 
  bridge:
    driver: bridge
