version: "3.7"

services:
  mysql:
    image: mysql:8.0.22
    ports:
      - 33306:3306
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 1010
      MYSQL_DATABASE: laravel
    networks:
      - bridge

  app:
    build: 
      context: ./bikes-app
      args:
        user: bikes
        uid: 1000
    ports:
      - 9000:9000
      - 9001:9001
    working_dir: /var/www/html
    volumes:
      - ./bikes/:/var/www/html
      - ./after-start.sh:/tmp/after-start.sh
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1010
      MYSQL_DB: laravel
    links:
      - mysql
    networks:
      - bridge
    depends_on:
      - mysql   
      
  web:
    image: nginx:1.19-alpine
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    ports:
      - 8000:80
    volumes:
      - ./bikes/:/var/www/html
      - ./nginx/conf/laravel.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
      - mysql
    networks:
      - bridge

networks: 
  bridge:
    driver: bridge
